### ISSUE TITLE
SNARK doesn't work

### ISSUE THREAD

**Issue by ddsvetlov** [sikoba/isekai#18]
Hello,
I tried to run isekai with simple example, which you described in your README.md in medium post (https://medium.com/sikoba-network/first-steps-with-isekai-on-windows-e9e5ab2c64d7).
So i tried to build docker and snark doesn't work, but the Bulletproof works.
Link to my repo: https://github.com/ddsvetlov/isekaii
There are test file zkex.c (same as in medium post)

#include "zkex.h"
void outsource(struct Input *input, struct NzikInput *nzik, struct Output *output)
{
 output->x = input->d + nzik->a + 5 - nzik->b * 2;
}

zkex.h(same as in medium post)

#pragma once
struct Input {
 int d;
};
struct NzikInput {
 int a, b;
};
struct Output {
 int x;
};
void outsource(struct Input *input, struct NzikInput *nzik, struct Output *output);

zkeh.c.in(same as in medium post)

11
5
17

Dockerfile you can find in repo.
So how to build and run project with SNARK without errors?
So command make test doesn't work too.

**Comment by guipublic** [comment]
Hello,

Thank you for your feedback, I have noticed that the provided library which wraps the SNARKs calls for isekai does not work on all systems. If you build it yourself it should be fine.
In order to build it, got to lib/libsnarc and then do the following:
mkdir build
cd build
cmake ..
make
Note that this library needs libsnark and libiop submodules so make sure you retrieved them recursively. One last point is that you would also need libsodium:
sudo apt-get install libsodium-dev

**Comment by ddsvetlov** [comment]
Thank you for quick responce.

All libraries install correctly. But after make libsnark, command that generated prove doesn't work yet.
So I updated repo and you can see new dockerfile

**Comment by guipublic** [comment]
Could you check the following:
- make sure you rebuild isekai after you built libsnarc library (make --always-make)
- what is the result with the following schemes:
isekai --prove=proof_file r1cs_file --scheme=bctv14a 
isekai --prove=proof_file r1cs_file --scheme=groth16
Note the the r1cs for bulletproof will not work for these two SNARKs. You need to generate it with the correct scheme: isekai --r1cs=r1cs_file source_file --scheme=bctv14a (then it will work for all SNARK schemes, only bullletproof r1cs is different).

**Comment by ddsvetlov** [comment]
Thank you, it works. 
So the problem was in schemes --scheme=bctv14a.
